In [4]:
import pandas as pd

In [ ]:
#1
student_df = pd.DataFrame({"Name":["Yanshul", "Ravindra", "Raj", "Shivesh"],
                           "Age":[18,19,20,21],
                           "City":["Aligarh", "Etawah", "Aligarh", "Mathura"]})

In [ ]:
#2
print(student_df)

       Name  Age     City
0   Yanshul   18  Aligarh
1  Ravindra   19   Etawah
2       Raj   20  Aligarh
3   Shivesh   21  Mathura

In [ ]:
#3
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [ ]:
#4
student_df['Name']

0     Yanshul
1    Ravindra
2         Raj
3     Shivesh
Name: Name, dtype: object

In [ ]:
#5
student_df['City']

0    Aligarh
1     Etawah
2    Aligarh
3    Mathura
Name: City, dtype: object

In [ ]:
#6
stud_df = student_df[['Name', 'City']]
print(stud_df)

       Name     City
0   Yanshul  Aligarh
1  Ravindra   Etawah
2       Raj  Aligarh
3   Shivesh  Mathura

In [ ]:
#7
book_df = pd.DataFrame({'Book':["Book1", "Book2", "Book3"], "Author":["Author1", "Author2", "Author3"], "Price":[100,200,300]})

In [ ]:
#8
book_df["Publisher"] = "Publisher Name"

    Book   Author  Price       Publisher
0  Book1  Author1    100  Publisher Name
1  Book2  Author2    200  Publisher Name
2  Book3  Author3    300  Publisher Name

In [ ]:
#9
import numpy as np
dict = pd.DataFrame({"SerialNo" : np.arange(5)})
print(dict)

   SerialNo
0         0
1         1
2         2
3         3
4         4

In [14]:
#1
import pandas as pd
student_df = pd.DataFrame({
    "Name" : ["Yanshul", "Raj", "Divya", "Yash"],
    "Age" : [18, 20, 19, 17],
    "City" : ["Aligarh", "Mathura", "Aligarh", "Hathras"]
})

In [15]:
#2
student_df

      Name  Age     City
0  Yanshul   18  Aligarh
1      Raj   20  Mathura
2    Divya   19  Aligarh
3     Yash   17  Hathras

In [16]:
#3
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [17]:
#4
student_df["Name"]

0    Yanshul
1        Raj
2      Divya
3       Yash
Name: Name, dtype: object

In [18]:
#5
student_df["City"]

0    Aligarh
1    Mathura
2    Aligarh
3    Hathras
Name: City, dtype: object

In [19]:
#6
student = student_df[["Name", "City"]]
student

      Name     City
0  Yanshul  Aligarh
1      Raj  Mathura
2    Divya  Aligarh
3     Yash  Hathras

In [20]:
#7
book_df = pd.DataFrame({
    "Book" : ["Book1", "Book2", "Book3"],
    "Author" : ["Author1", "Author2", "Author3"],
    "Price" : [100, 200, 300]
})

In [21]:
#8
book_df["Publisher"] = "ABC"

In [22]:
#9
import numpy as np
new = pd.DataFrame({"SerialNo" : np.arange(5)})
new

   SerialNo
0         0
1         1
2         2
3         3
4         4

In [23]:
#10
new.drop(columns=["SerialNo"], inplace=True)

In [24]:
#11
movie_df = pd.DataFrame({
    "Movie": ["Movie1", "Movie2", "Movie3"],
    "Year": [2024, 2025, 2026],
    "Rating": [8.5, 7.8, 9.0]
})

In [25]:
#12
movie_df = movie_df.reindex(columns=["Movie", "Rating", "Director"])

In [26]:
#13
city_series = pd.Series(["Mathura", "Aligarh"], index=[0, 3])

In [27]:
#14
student_df["Branch"] = city_series

In [30]:
#15
copied_df = pd.read_clipboard()

In [31]:
#16
employee_df = pd.DataFrame({
    "Employee": ["Aman", "Rohan", "Priya", "Neha", "Karan"],
    "Department": ["IT", "HR", "Finance", "Sales", "Marketing"],
    "Experience": [2, 4, 3, 5, 1]
})

new_emp_df = employee_df[["Employee", "Experience"]]
display(new_emp_df)

  Employee  Experience
0     Aman           2
1    Rohan           4
2    Priya           3
3     Neha           5
4    Karan           1

In [32]:
#17
dept_col = employee_df["Department"]
# ya phir dot notation: dept_col = employee_df.Department

print(employee_df.columns)

Index(['Employee', 'Department', 'Experience'], dtype='object')

In [33]:
#18
employee_df["Office"] = "Head Office"
display(employee_df)

  Employee Department  Experience       Office
0     Aman         IT           2  Head Office
1    Rohan         HR           4  Head Office
2    Priya    Finance           3  Head Office
3     Neha      Sales           5  Head Office
4    Karan  Marketing           1  Head Office

In [34]:
#19
import numpy as np

employee_df["Office"] = np.arange(5)
display(employee_df)

  Employee Department  Experience  Office
0     Aman         IT           2       0
1    Rohan         HR           4       1
2    Priya    Finance           3       2
3     Neha      Sales           5       3
4    Karan  Marketing           1       4

In [35]:
#20
office_names = pd.Series(["Delhi", "Mumbai", "Pune"], index=[0, 2, 4])

employee_df["Office"] = office_names
display(employee_df)

  Employee Department  Experience  Office
0     Aman         IT           2   Delhi
1    Rohan         HR           4     NaN
2    Priya    Finance           3  Mumbai
3     Neha      Sales           5     NaN
4    Karan  Marketing           1    Pune

In [36]:
#21
employee_df = employee_df.drop(columns=["Office"])
display(employee_df.columns)
# ya phir poora DataFrame dekhne ke liye: display(employee_df)

Index(['Employee', 'Department', 'Experience'], dtype='object')

In [37]:
#22
product_df = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard"],
    "Category": ["Electronics", "Accessories", "Accessories"],
    "Price": [50000, 500, 1500]
})

reordered_df = product_df[["Price", "Product", "Category"]]
display(reordered_df)

   Price   Product     Category
0  50000    Laptop  Electronics
1    500     Mouse  Accessories
2   1500  Keyboard  Accessories

In [38]:
#23
# student_df mein 'Grade' column nahi hai, toh reindex ka use karenge
missing_col_df = student_df.reindex(columns=["Name", "Age", "City", "Grade"])
display(missing_col_df)

      Name  Age     City  Grade
0  Yanshul   18  Aligarh    NaN
1      Raj   20  Mathura    NaN
2    Divya   19  Aligarh    NaN
3     Yash   17  Hathras    NaN

In [39]:
#24
marks_df = pd.DataFrame({
    "Name": ["Yanshul", "Raj", "Divya"],
    "Total Marks": [85, 90, 88]
})

# Square bracket notation ka use karna hoga kyunki naam mein space hai
display(marks_df["Total Marks"])

0    85
1    90
2    88
Name: Total Marks, dtype: int64

In [41]:
#25
# Agar pd.read_clipboard() error de, toh ye use karein:
import io
data = input("Apna table paste karein:\n")
copied_df = pd.read_csv(io.StringIO(data), sep="\t")

# Columns display karna
print(copied_df.columns)

# Koi bhi 3 columns select karke naya DataFrame banana (apne table ke columns ke naam yahan likhein)
selected_three_df = copied_df[["Col1", "Col2", "Col3"]]
display(selected_three_df)

In [42]:
#26
course_df = pd.DataFrame({
    "Student": ["Aman", "Rohan", "Priya", "Neha", "Karan"],
    "Course": ["Python", "Java", "C++", "SQL", "AI"],
    "Score": [85, 90, 78, 88, 92]
})

print(course_df.columns)
display(course_df["Student"])

sub_course_df = course_df[["Student", "Score"]]
display(sub_course_df)

course_df["Batch"] = "Batch-A"
display(course_df)

Index(['Student', 'Course', 'Score'], dtype='object')

0     Aman
1    Rohan
2    Priya
3     Neha
4    Karan
Name: Student, dtype: object

  Student  Score
0    Aman     85
1   Rohan     90
2   Priya     78
3    Neha     88
4   Karan     92

  Student  Course  Score    Batch
0    Aman  Python     85  Batch-A
1   Rohan    Java     90  Batch-A
2   Priya     C++     78  Batch-A
3    Neha     SQL     88  Batch-A
4   Karan      AI     92  Batch-A

In [43]:
#27
travel_df = pd.DataFrame({
    "Destination": ["Agra", "Delhi", "Jaipur", "Mumbai", "Goa"],
    "Days": [2, 3, 4, 5, 6]
})

# np.arange(5) add karna
travel_df["Code"] = np.arange(5)
display(travel_df)

# Sirf index 1 aur 4 par values wali Series se replace karna
travel_df["Code"] = pd.Series([10, 40], index=[1, 4])
display(travel_df)

  Destination  Days  Code
0        Agra     2     0
1       Delhi     3     1
2      Jaipur     4     2
3      Mumbai     5     3
4         Goa     6     4

  Destination  Days  Code
0        Agra     2   NaN
1       Delhi     3  10.0
2      Jaipur     4   NaN
3      Mumbai     5   NaN
4         Goa     6  40.0

In [44]:
#28
school_df = pd.DataFrame({
    "Student": ["Amit", "Sumit", "Rahul", "Pooja", "Neha"],
    "Class": ["10th", "10th", "12th", "11th", "12th"],
    "Section": ["A", "B", "A", "C", "B"]
})

# Missing 'House' column ke sath reindex karna
school_df = school_df.reindex(columns=["Student", "Class", "Section", "House"])

# House column mein ek common value assign karna
school_df["House"] = "Red"
display(school_df)

  Student Class Section House
0    Amit  10th       A   Red
1   Sumit  10th       B   Red
2   Rahul  12th       A   Red
3   Pooja  11th       C   Red
4    Neha  12th       B   Red

In [45]:
#29
inventory_df = pd.DataFrame({
    "Item": ["Pen", "Pencil", "Eraser", "Notebook", "Scale"],
    "Quantity": [10, 20, 15, 30, 25]
})

# Partially indexed Series add karna (e.g., indexes 1 aur 3 par)
inventory_df["Discount"] = pd.Series([5.0, 10.0], index=[1, 3])
display(inventory_df)

# Column delete karna aur phir display karna
inventory_df = inventory_df.drop(columns=["Discount"])
display(inventory_df)

       Item  Quantity  Discount
0       Pen        10       NaN
1    Pencil        20       5.0
2    Eraser        15       NaN
3  Notebook        30      10.0
4     Scale        25       NaN

       Item  Quantity
0       Pen        10
1    Pencil        20
2    Eraser        15
3  Notebook        30
4     Scale        25

In [47]:
#30
import io
data = input("Apna table paste karein:\n")
lab_df = pd.read_csv(io.StringIO(data), sep="\t")

# Sequence of statements
display(lab_df)
print("Column Names:", lab_df.columns)
display(lab_df["SingleWordCol"])      # Apne table ke single-word column ka naam yahan likhein
display(lab_df["Column With Space"])  # Apne table ke space wale column ka naam yahan likhein

smaller_lab_df = lab_df[["Col1", "Col2"]] # Apne table ke hisaab se columns dein
display(smaller_lab_df)

lab_df["NewCol"] = 100
display(lab_df)

lab_df = lab_df.drop(columns=["NewCol"])
display(lab_df)